jasypt:
  encryptor:

##默认使用配置 https://blog.csdn.net/weixin_41461281/article/details/80453106
#spring:
#  profiles:
#    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.yuan.blog.domain
  mapperLocations: classpath:mapper/*.xml
  # mybatis 配置
  configLocation: classpath:mybatis-config.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

spring:
  mail:
    password: ENC(7gYxkFcG5AqheTVolmSzdNbygakrfaGOAL9iQdMdYE4=)
    host: smtp.qq.com
    username: ENC(NOAY9J3Gwa2Re1/GVQ0/Ou6H/umzFEWbVQdnb3q9f50=)
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true
          auth: true
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      properties:
        transport:
          tcp:
            connect_timeout: 1s
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
  resources:
    chain:
      cache: true
      gzipped: false
      html-application-cache: false
      strategy:
        fixed:
          paths: /**
          version: 1.0
          enabled: false
        content:
          paths: /**
          enabled: false
      enabled: true
    cache:
      cachecontrol:
        max-age: 1440s
    add-mappings: true
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
server:
  servlet:
    session:
      timeout: 2400H

logging:
  level:
    com:
      dy:
        springboot:
          server:
            mapper: debug
  config: classpath:log4j2.xml

---
#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

---
# 生产配置
spring:
  profiles: default
  datasource:
    url: ENC(2G4VbKAAVtTwPrSQER2WRJrjPh87TUUBlXOKGwiWiWCsD/6pap0Y9/3WS/7aZMaRRaZRIHZqUkOLdDdVgDQW7uBFHFSbKOK7dbfWjIm+sS3JHxDE+sFWv8Es4oQAkV7LaDY+tj035Sk=)
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    password: ENC(2ekiWt0lsaXt02jG4hxlsO7WlKO/b4d8)
